# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 苇名一心的博客
subtitle:
description: '经验分享和技术交流。'
keywords: '计算机,IT,学习交流,Blog,博客'
author: '苇名一心'
language: zh-CN
timezone: ''
favicon: https://cdn.jsdelivr.net/gh/666WXY666/cdn/img/favicon/favicon.ico
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://666wxy666.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - manifest.json
  - start
  - CNAME
  - robots.txt
  - assets/*

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: volantis

# hexo-deployer-git
deploy:
  type: git
  repo: git@github.com:666WXY666/666WXY666.github.io.git
  branch: master
  message: "Github CI Auto Builder at {{ now('YYYY-MM-DD HH:mm:ss Z') }}"

# hexo-git-backup
backup:
  type: git
  theme: volantis
  message: Backup My Blog
  repository:
    github: git@github.com:666WXY666/666WXY666.github.io.git,backup

# Security
# hexo-blog-encrypt
encrypt:
  enable: true
  abstract: <p>这篇文章被加密了, 请输入密码查看。</p>
  message: 在这里输入正确的密码，才能查看这篇文章哦：
  tags:
  - {name: tagName, password: 密码A}
  - {name: tagName, password: 密码B}
  template: <div id="hexo-blog-encrypt" data-wpm="{{hbeWrongPassMessage}}" data-whm="{{hbeWrongHashMessage}}"><div class="hbe-input-container"><input type="password" id="hbePass" placeholder="{{hbeMessage}}" /><label>{{hbeMessage}}</label><div class="bottom-line"></div></div><script id="hbeData" type="hbeData" data-hmacdigest="{{hbeHmacDigest}}">{{hbeEncryptedData}}</script></div>
  wrong_pass_message: 密码好像不太对呢, 请再试试。
  wrong_hash_message: 这篇文章不能被校验, 不过您还是能看看解密后的内容。

# 百度统计
baidu_analytics_key: 93c49980dcbfb8920e167f85129d6917

# 谷歌分析
google_analytics_key: UA-162450234-2

use_cdn: true

# 网站地图
# npm install hexo-generator-sitemap --save
# npm install hexo-generator-baidu-sitemap --save
sitemap:
	path: sitemap.xml
baidusitemap:
	path: baidusitemap.xml

# 图片懒加载  
# hexo-lazyload-image
lazyload:
  enable: true
  onlypost: false
  loadingImg: https://cdn.jsdelivr.net/gh/666WXY666/cdn/img/placeholder/large.svg

# npm install hexo-all-minifier --save
# 静态资源压缩
all_minifier: true

js_concator:
  enable: false
  bundle_path: '/js/bundle.js'
  front: false
  silent: false

html_minifier:            # html压缩
  enable: true
  ignore_error: false
  silent: false
  exclude: 

css_minifier:         # css压缩
  enable: true
  silent: false
  exclude: 
    - '*.min.css'

js_minifier:          # js压缩
  enable: true
  mangle: true
  silent: false
  output:
  compress:
  exclude: 
    - '*.min.js'

image_minifier:           # 图片压缩
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false
  silent: false


# hexo-autonofollow
nofollow:
  enable: true
  exclude: # 例外的链接，可将友情链接放置此处
    - 666WXY666.github.io
    - wxy_666.gitee.io

# hexo-autoprefixer
autoprefixer:
  exclude:
    - '*.min.css'

# offline config passed to sw-precache.
# hexo-offline
offline:
  maximumFileSizeToCacheInBytes: 10485760
  staticFileGlobs:
    - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
  stripPrefix: public
  verbose: true
  runtimeCaching:
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdn.jsdelivr.net
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: cdnjs.cloudflare.com

marked:
  gfm: true
  pedantic: false
  breaks: true
  smartLists: true
  smartypants: true
  modifyAnchors: 0
  autolink: true
  sanitizeUrl: false
  headerIds: true
  prependRoot: false
  external_link:
    enable: true
    exclude: []
    nofollow: true

# RSS订阅
# Feed Atom
# hexo-generator-feed
feed:
type: atom
path: atom.xml
limit: 20